/*JEZICI*/
    
function change_text_cro(){
    document.getElementById("seeMore").innerHTML = "Saznaj više";
    document.getElementById("seeMore2").innerHTML = "Saznaj više";
    document.getElementById("seeMore3").innerHTML = "Saznaj više";
    document.getElementById("stosija").innerHTML = "Sveta Stošija ili Sveta Anastazija bila je kršćanska mučenica i svetica koja je umrla u Sirmiumu za vrijeme Dioklecijanovih progona. <br>U Hrvatskoj je poznata kao Sveta Stošija. <br><br> O Anastazijinom životu, osim vremena njene smrti, ima malo pouzdanih podataka. Umjesto toga postoje legende, uglavnom datirane stoljećima nakon njene smrti. Po njima je bila rodom iz Rima ili Sirmiuma, odnosno rimska građanka patricijskog ranga. Prema jednoj legendi je bila kćer nekog Preteksta i učenica Svetog Krševana (Krizogon). U katoličkoj tradiciji navodi se da joj je majka bila sv. Fausta iz Sirmijuma.";
    document.getElementById("stosija2").innerHTML ="Na najvišoj uzvisini biogradskoga poluotoka u središtu grada nalazi se župna crkva sv. Stošije posvećena 1761. g. Oko crkve su ostatci groblja iz 6. st., a uz crkvu je visoki kameni zvonik izgrađen od kamenja nekadašnje biogradske katedrale koja je bila na tom mjestu. Kamen te katedrale podignute na temeljima starokršćanske crkve ugrađen je i u župnu crkvu na čijem je vrhu pročelja kip sv. Stošije, a župa posjeduje i svetičin relikvijar. Čašćenje sv. Stošije donijeli su Zadrani koji su se sklonili u Biograd u 12. st. kad su Mlečani srušili Zadar.";
    document.getElementById("stosijaNaslov").innerHTML = "Crkva sv. Stošije";
    document.getElementById("moreStosija").innerHTML = "<br><br>Sveta Stošija ili Sveta Anastazija bila je kršćanska mučenica i svetica koja je umrla u Sirmiumu za vrijeme Dioklecijanovih progona. U Hrvatskoj je poznata kao Sveta Stošija. <br><br><br>Na najvišoj uzvisini biogradskoga poluotoka u središtu grada nalazi se župna crkva sv. Stošije posvećena 1761. g. Oko crkve su ostatci groblja iz 6. st., a uz crkvu je visoki kameni zvonik izgrađen od kamenja nekadašnje biogradske katedrale koja je bila na tom mjestu. Kamen te katedrale podignute na temeljima starokršćanske crkve ugrađen je i u župnu crkvu na čijem je vrhu pročelja kip sv. Stošije, a župa posjeduje i svetičin relikvijar. Čašćenje sv. Stošije donijeli su Zadrani koji su se sklonili u Biograd u 12. st. kad su Mlečani srušili Zadar.";
    document.getElementById("muzejNaslov").innerHTML = "Zavičajni muzej";
    document.getElementById("muzej").innerHTML = " Zavičajni muzej Grada Biograda na Moru, samostalna je i jedina ustanova u kulturi na biogradskom području. Čuva vrijednu spomeničku baštinu iz bogate prošlosti biogradskog primorja i okolice. <br> <br> <br> Smješten je u centralnom djelu, na samoj obali Biograda, nekadašnjeg kraljevskog i krunidbenog grada, prijestolnice hrvatske države za narodnih vladara u 11. stoljeću. Sama zgrada u kojoj je smješten Muzej spada u spomenik kulture. Podignuta je na ruševinama srednjovjekovnih zidina pri kraju 18. i početkom 19. stoljeća. U njoj je dugi niz godina djelovao Kotarski sud uspostavljen za cara i kralja Franje Josipa I -1876. godine.";
    document.getElementById("moreMuzej").innerHTML = " <br>Zavičajni muzej Grada Biograda na Moru, samostalna je i jedina ustanova u kulturi na biogradskom području. Čuva vrijednu spomeničku baštinu iz bogate prošlosti biogradskog primorja i okolice. <br> <br> <br> Smješten je u centralnom djelu, na samoj obali Biograda, nekadašnjeg kraljevskog i krunidbenog grada, prijestolnice hrvatske države za narodnih vladara u 11. stoljeću. Sama zgrada u kojoj je smješten Muzej spada u spomenik kulture. Podignuta je na ruševinama srednjovjekovnih zidina pri kraju 18. i početkom 19. stoljeća. U njoj je dugi niz godina djelovao Kotarski sud uspostavljen za cara i kralja Franje Josipa I -1876. godine.";
    document.getElementById("rokoNaslov").innerHTML = "Crkva sv. Roka ";
    document.getElementById("roko").innerHTML = " <br>Najraniji spomen crkve nalazi se u oporuci pisanoj 1653. godine, u kojoj Franica, žena Ivana Senjanina, ostavlja urod od maslina: „Crikvi svetoga Roka ka je prid selom našim“. <br><br> Posvećena svetom Roku, zaštitniku od kuge, sagrađena je krajem 16. ili početkom 17. stoljeća. Unutrašnjošću crkve dominira pozlaćeni barokni oltar iz 18. stoljeća. a oko crkvice nalazi se nekoliko stabala sa klupama za sjedenje, pa cijeli prostor odaje dojam mini parka. ";
    document.getElementById("moreRoko").innerHTML = " <br><br><br>Najraniji spomen crkve nalazi se u oporuci pisanoj 1653. godine, u kojoj Franica, žena Ivana Senjanina, ostavlja urod od maslina: „Crikvi svetoga Roka ka je prid selom našim“. <br><br> Posvećena svetom Roku, zaštitniku od kuge, sagrađena je krajem 16. ili početkom 17. stoljeća. Unutrašnjošću crkve dominira pozlaćeni barokni oltar iz 18. stoljeća. a oko crkvice nalazi se nekoliko stabala sa klupama za sjedenje, pa cijeli prostor odaje dojam mini parka. ";
    document.getElementById("location").innerHTML = "Upute do lokacije";
    document.getElementById("location2").innerHTML = "Upute do lokacije";
    document.getElementById("location3").innerHTML = "Upute do lokacije";
}

function change_text_eng(){
    document.getElementById("seeMore").innerHTML = "See more";
    document.getElementById("seeMore2").innerHTML = "See more";
    document.getElementById("seeMore3").innerHTML = "See more";
    document.getElementById("stosija").innerHTML = "Saint Stoshia or Saint Anastasia was a Christian martyr and saint who died in Sirmium during the persecutions of Diocletian. In Croatia, it is known as Sveta Stošija.<br>In Croatia, it is known as Sveta Stošija. <br><br> There is little reliable information about Anastasia's life, apart from the time of her death. Instead there are legends, mostly dated centuries after her death. According to them, she was a native of Rome or Sirmium, that is, a Roman citizen of patrician rank. According to one legend, she was the daughter of a certain Pretext and a student of St. Krševan (Chryzogon). In the Catholic tradition, it is stated that her mother was St. Faust of Sirmium."; 
    document.getElementById("stosija2").innerHTML ="On the highest elevation of the Biograd peninsula in the city center is the parish church of St. Stošija was consecrated in 1761. Around the church are the remains of a cemetery from the 6th century, and next to the church is a high stone belfry built from the stones of the former Biograd cathedral that was on that site. The stone of that cathedral, built on the foundations of an early Christian church, was also incorporated into the parish church, on the top of the facade of which is a statue of St. Stošija, and the parish also owns the saint's reliquary. Veneration of St. The remains were brought by the people of Zadar who took refuge in Biograd in the 12th century when the Venetians overthrew Zadar.";
    document.getElementById("stosijaNaslov").innerHTML = "Church of St. Stosija (St. Anastasia)";
    document.getElementById("moreStosija").innerHTML = "<br><br>Sveta Stošija ili Sveta Anastazija bila je kršćanska mučenica i svetica koja je umrla u Sirmiumu za vrijeme Dioklecijanovih progona. U Hrvatskoj je poznata kao Sveta Stošija. <br><br><br>Na najvišoj uzvisini biogradskoga poluotoka u središtu grada nalazi se župna crkva sv. Stošije posvećena 1761. g. Oko crkve su ostatci groblja iz 6. st., a uz crkvu je visoki kameni zvonik izgrađen od kamenja nekadašnje biogradske katedrale koja je bila na tom mjestu. Kamen te katedrale podignute na temeljima starokršćanske crkve ugrađen je i u župnu crkvu na čijem je vrhu pročelja kip sv. Stošije, a župa posjeduje i svetičin relikvijar. Čašćenje sv. Stošije donijeli su Zadrani koji su se sklonili u Biograd u 12. st. kad su Mlečani srušili Zadar.";
    document.getElementById("muzejNaslov").innerHTML = "Heritage Museum";
    document.getElementById("muzej").innerHTML = "  The Native Museum of the City of Biograd na Moru is an independent and the only cultural institution in the Biograd area. It preserves valuable monumental heritage from the rich past of the Biograd coast and its surroundings. <br> <br> <br> It is located in the central part, on the very coast of Biograd, the former royal and coronation city, the capital of the Croatian state for the people's rulers in the 11th century. The very building in which the Museum is located is a cultural monument. It was built on the ruins of the medieval walls at the end of the 18th and the beginning of the 19th century. For many years, the District Court established for Emperor and King Francis Josip I - 1876 operated in it years.";
    document.getElementById("moreMuzej").innerHTML = " Zavičajni muzej Grada Biograda na Moru, samostalna je i jedina ustanova u kulturi na biogradskom području. Čuva vrijednu spomeničku baštinu iz bogate prošlosti biogradskog primorja i okolice. <br> <br> <br> Smješten je u centralnom djelu, na samoj obali Biograda, nekadašnjeg kraljevskog i krunidbenog grada, prijestolnice hrvatske države za narodnih vladara u 11. stoljeću. Sama zgrada u kojoj je smješten Muzej spada u spomenik kulture. Podignuta je na ruševinama srednjovjekovnih zidina pri kraju 18. i početkom 19. stoljeća. U njoj je dugi niz godina djelovao Kotarski sud uspostavljen za cara i kralja Franje Josipa I -1876. godine.";
    document.getElementById("rokoNaslov").innerHTML = "Church Of St. Roko (St. Rocco)";
    document.getElementById("roko").innerHTML = " The first written record of this tiny church may be found in a will dated 1653 in which Franica, the wife of Ivana Senjanina, left behind in her will: To the „To the Church of St. Rocco, which is in front of our village.“. <br> <br> St. Rocco is the saint best known as the protector from the plague. The church was built in the late 16th or early 17th century. The church interior is dominated by a gold leaf baroque-style altar from the 18th century, and around the church there are several trees with benches for sitting, so the whole area gives the impression of a mini park.";
    document.getElementById("moreRoko").innerHTML = " <br><br><br>Najraniji spomen crkve nalazi se u oporuci pisanoj 1653. godine, u kojoj Franica, žena Ivana Senjanina, ostavlja urod od maslina: „Crikvi svetoga Roka ka je prid selom našim“. <br><br> Posvećena svetom Roku, zaštitniku od kuge, sagrađena je krajem 16. ili početkom 17. stoljeća. Unutrašnjošću crkve dominira pozlaćeni barokni oltar iz 18. stoljeća. a oko crkvice nalazi se nekoliko stabala sa klupama za sjedenje, pa cijeli prostor odaje dojam mini parka. ";
    document.getElementById("location").innerHTML = "Directions";
    document.getElementById("location2").innerHTML = "Directions";
    document.getElementById("location3").innerHTML = "Directions";
}

function change_text_it(){
    document.getElementById("seeMore").innerHTML = "Vedi altro";
    document.getElementById("seeMore2").innerHTML = "Vedi altro";
    document.getElementById("seeMore3").innerHTML = "Vedi altro";
    document.getElementById("stosija").innerHTML = "Santa Stoshia o Santa Anastasia era una martire e santa cristiana morta a Sirmio durante le persecuzioni di Diocleziano. In Croazia è conosciuta come Sveta Stošija. <br>In Croazia, è conosciuta come Sveta Stošija. <br><br> Ci sono poche informazioni attendibili sulla vita di Anastasia, a parte l'ora della sua morte. Ci sono invece leggende, per lo più datate secoli dopo la sua morte. Secondo loro era originaria di Roma o di Sirmio, cioè cittadina romana di rango patrizio. Secondo una leggenda, era la figlia di un certo pretesto e una studentessa di San Krševan (Chryzogon). Nella tradizione cattolica, si afferma che sua madre fosse S. Faust di Sirmio."
    document.getElementById("stosija2").innerHTML ="Sulla più alta elevazione della penisola di Biograd, nel centro della città, si trova la chiesa parrocchiale di S. Stošija fu consacrata nel 1761. Intorno alla chiesa ci sono i resti di un cimitero del VI secolo, e accanto alla chiesa c'è un alto campanile in pietra costruito con le pietre dell'ex cattedrale di Biograd che si trovava in quel sito. La pietra di quella cattedrale, edificata sulle fondamenta di una chiesa paleocristiana, fu inglobata anche nella chiesa parrocchiale, sulla cui sommità della facciata si trova una statua di S. Stošija, e la parrocchia possiede anche il reliquiario del santo. Venerazione di S. I resti furono portati dagli abitanti di Zara che si rifugiarono a Biograd nel XII secolo quando i veneziani rovesciarono Zara.";
    document.getElementById("stosijaNaslov").innerHTML = "Chiesa di Sant'Anastasia";
    document.getElementById("moreStosija").innerHTML = "<br><br>Sveta Stošija ili Sveta Anastazija bila je kršćanska mučenica i svetica koja je umrla u Sirmiumu za vrijeme Dioklecijanovih progona. U Hrvatskoj je poznata kao Sveta Stošija. <br><br><br>Na najvišoj uzvisini biogradskoga poluotoka u središtu grada nalazi se župna crkva sv. Stošije posvećena 1761. g. Oko crkve su ostatci groblja iz 6. st., a uz crkvu je visoki kameni zvonik izgrađen od kamenja nekadašnje biogradske katedrale koja je bila na tom mjestu. Kamen te katedrale podignute na temeljima starokršćanske crkve ugrađen je i u župnu crkvu na čijem je vrhu pročelja kip sv. Stošije, a župa posjeduje i svetičin relikvijar. Čašćenje sv. Stošije donijeli su Zadrani koji su se sklonili u Biograd u 12. st. kad su Mlečani srušili Zadar.";
    document.getElementById("muzejNaslov").innerHTML = "Il Museo della Patria";
    document.getElementById("muzej").innerHTML = " Il Museo nativo della città di Biograd na Moru è un'istituzione culturale indipendente e l'unica nell'area di Biograd. Conserva un prezioso patrimonio monumentale del ricco passato della costa di Biograd e dei suoi dintorni. <br> <br> <br> Si trova nella parte centrale, proprio sulla costa di Biograd, l'antica città reale e dell'incoronazione, la capitale dello stato croato per i governanti del popolo nell'XI secolo. L'edificio stesso in cui si trova il Museo è un monumento culturale. Fu costruito sui resti delle mura medievali tra la fine del XVIII e l'inizio del XIX secolo. Per molti anni vi operò il tribunale distrettuale istituito per l'imperatore e il re Francesco Josip I - nel 1876";
    document.getElementById("moreMuzej").innerHTML = "  Zavičajni muzej Grada Biograda na Moru, samostalna je i jedina ustanova u kulturi na biogradskom području. Čuva vrijednu spomeničku baštinu iz bogate prošlosti biogradskog primorja i okolice. <br> <br> <br> Smješten je u centralnom djelu, na samoj obali Biograda, nekadašnjeg kraljevskog i krunidbenog grada, prijestolnice hrvatske države za narodnih vladara u 11. stoljeću. Sama zgrada u kojoj je smješten Muzej spada u spomenik kulture. Podignuta je na ruševinama srednjovjekovnih zidina pri kraju 18. i početkom 19. stoljeća. U njoj je dugi niz godina djelovao Kotarski sud uspostavljen za cara i kralja Franje Josipa I -1876. godine.";
    document.getElementById("rokoNaslov").innerHTML = "Chiesa di San Rocco";
    document.getElementById("roko").innerHTML = " <br>Vale a dire, la prima menzione della chiesa fu scritta in un testamento nel 1653, in cui Franica, moglie di Ivan Senjan, lasciò un raccolto di ulivi: „Alla Chiesa di San Rocco, che si trova di fronte al nostro villaggio.“. <br><br> Dedicata a San Rocco, il santo patrono della peste, fu costruita alla fine del XVI o all'inizio del XVII secolo. L'interno della chiesa è dominato da un altare dorato in stile barocco del XVIII secolo, e intorno alla chiesa ci sono diversi alberi con panchine per sedersi, quindi l'intera area dà l'impressione di un mini parco.";
    document.getElementById("moreRoko").innerHTML = " <br><br><br>Najraniji spomen crkve nalazi se u oporuci pisanoj 1653. godine, u kojoj Franica, žena Ivana Senjanina, ostavlja urod od maslina: „Crikvi svetoga Roka ka je prid selom našim“. <br><br> Posvećena svetom Roku, zaštitniku od kuge, sagrađena je krajem 16. ili početkom 17. stoljeća. Unutrašnjošću crkve dominira pozlaćeni barokni oltar iz 18. stoljeća. a oko crkvice nalazi se nekoliko stabala sa klupama za sjedenje, pa cijeli prostor odaje dojam mini parka. ";
    document.getElementById("location").innerHTML = "Indicazioni stradali" ;
    document.getElementById("location2").innerHTML = "Indicazioni stradali ";
    document.getElementById("location3").innerHTML = "Indicazioni stradali ";
}

function change_text_de(){
    document.getElementById("seeMore").innerHTML = "Mehr sehen";
    document.getElementById("seeMore2").innerHTML = "Mehr sehen";
    document.getElementById("seeMore3").innerHTML = "Mehr sehen";
    document.getElementById("stosija").innerHTML = "Die heilige Stoshia oder die heilige Anastasia war eine christliche Märtyrerin und Heilige, die während der Verfolgungen Diokletians in Sirmium starb. In Kroatien ist es als Sveta Stošija bekannt.<br>In Kroatien ist es als Sveta Stošija bekannt. <br><br> Außer dem Zeitpunkt ihres Todes gibt es nur wenige verlässliche Informationen über Anastasias Leben. Stattdessen gibt es Legenden, die meist Jahrhunderte nach ihrem Tod datieren. Ihren Angaben zufolge stammte sie aus Rom oder Sirmium, war also eine römische Bürgerin im Patrizierstand. Einer Legende zufolge war sie die Tochter eines gewissen Vorwands und eine Schülerin des heiligen Krševan (Chryzogon). In der katholischen Tradition heißt es, dass ihre Mutter die heilige St. Faust von Sirmium." ;
    document.getElementById("stosija2").innerHTML ="Auf der höchsten Erhebung der Halbinsel Biograd im Stadtzentrum befindet sich die Pfarrkirche St. Stošija wurde 1761 geweiht. Rund um die Kirche befinden sich die Überreste eines Friedhofs aus dem 6. Jahrhundert, und neben der Kirche befindet sich ein hoher steinerner Glockenturm, der aus den Steinen der ehemaligen Kathedrale von Biograd an dieser Stelle errichtet wurde. Der Stein dieser Kathedrale, die auf den Fundamenten einer frühchristlichen Kirche errichtet wurde, wurde auch in die Pfarrkirche integriert, an deren Fassade sich eine Statue des Heiligen befindet. Stošija, und die Pfarrei besitzt auch das Reliquiar des Heiligen. Verehrung des hl. Die Überreste wurden von den Einwohnern von Zadar mitgebracht, die im 12. Jahrhundert nach der Eroberung Zadars durch die Venezianer in Biograd Zuflucht suchten.";
    document.getElementById("stosijaNaslov").innerHTML = "Kirche der Heiligen Anastasia";
    document.getElementById("moreStosija").innerHTML = "<br><br>Sveta Stošija ili Sveta Anastazija bila je kršćanska mučenica i svetica koja je umrla u Sirmiumu za vrijeme Dioklecijanovih progona. U Hrvatskoj je poznata kao Sveta Stošija. <br><br><br>Na najvišoj uzvisini biogradskoga poluotoka u središtu grada nalazi se župna crkva sv. Stošije posvećena 1761. g. Oko crkve su ostatci groblja iz 6. st., a uz crkvu je visoki kameni zvonik izgrađen od kamenja nekadašnje biogradske katedrale koja je bila na tom mjestu. Kamen te katedrale podignute na temeljima starokršćanske crkve ugrađen je i u župnu crkvu na čijem je vrhu pročelja kip sv. Stošije, a župa posjeduje i svetičin relikvijar. Čašćenje sv. Stošije donijeli su Zadrani koji su se sklonili u Biograd u 12. st. kad su Mlečani srušili Zadar.";
    document.getElementById("muzejNaslov").innerHTML = "Das Heimatmuseums";
    document.getElementById("muzej").innerHTML = " Das Heimatmuseum der Stadt Biograd na Moru ist eine unabhängige und einzige Kultureinrichtung in der Region Biograd. Es bewahrt wertvolles Denkmalerbe aus der reichen Vergangenheit der Küste von Biograd und ihrer Umgebung. <br> <br> <br> Es liegt im zentralen Teil, direkt an der Küste von Biograd, der ehemaligen Königs- und Krönungsstadt, der Hauptstadt des kroatischen Staates für die Volksherrscher im 11. Jahrhundert. Das Gebäude, in dem sich das Museum befindet, ist ein Kulturdenkmal. Es wurde Ende des 18. und Anfang des 19. Jahrhunderts auf den Ruinen der mittelalterlichen Mauern erbaut. Viele Jahre lang war dort das Bezirksgericht für Kaiser und König Franz Josip I. tätig – 1876 war es dort tätig.";
    document.getElementById("moreMuzej").innerHTML = " Zavičajni muzej Grada Biograda na Moru, samostalna je i jedina ustanova u kulturi na biogradskom području. Čuva vrijednu spomeničku baštinu iz bogate prošlosti biogradskog primorja i okolice. <br> <br> <br> Smješten je u centralnom djelu, na samoj obali Biograda, nekadašnjeg kraljevskog i krunidbenog grada, prijestolnice hrvatske države za narodnih vladara u 11. stoljeću. Sama zgrada u kojoj je smješten Muzej spada u spomenik kulture. Podignuta je na ruševinama srednjovjekovnih zidina pri kraju 18. i početkom 19. stoljeća. U njoj je dugi niz godina djelovao Kotarski sud uspostavljen za cara i kralja Franje Josipa I -1876. godine.";
    document.getElementById("rokoNaslov").innerHTML = "Kirche des heiligen Roko (Rochus)";
    document.getElementById("roko").innerHTML = "   Die früheste Erwähnung der Kirche stammt nämich aus einem 1653 verfassten Testament, in dem Franica, die Frau von Ivan Senjan, die gesamete Olivenernte der Kirche hinterlässt: „Zur Kirche St. Rochus, die vor unserem Dorf liegt.“ <br><br> Die Kirche ist dem heiligen Rocco, dem Schutzpatron vor der Pest, gewidt und wurde Ende des 16. oder Anfang des 17. Jahrhunderts erbaut. Im Inneren der Kirche dominiert ein vergoldeter Barockaltar aus dem 18. Jahrhundert. Rund um die Kirche stehen mehrere Bäume mit Sitzbänken, so dass die gesamte Anlage den Eindruck eines Miniparks vermittelt.";
    document.getElementById("moreRoko").innerHTML = " <br><br><br>Najraniji spomen crkve nalazi se u oporuci pisanoj 1653. godine, u kojoj Franica, žena Ivana Senjanina, ostavlja urod od maslina: „Crikvi svetoga Roka ka je prid selom našim“. <br><br> Posvećena svetom Roku, zaštitniku od kuge, sagrađena je krajem 16. ili početkom 17. stoljeća. Unutrašnjošću crkve dominira pozlaćeni barokni oltar iz 18. stoljeća. a oko crkvice nalazi se nekoliko stabala sa klupama za sjedenje, pa cijeli prostor odaje dojam mini parka. ";
    document.getElementById("location").innerHTML = "Wegbeschreibung";
    document.getElementById("location2").innerHTML = "Wegbeschreibung";
    document.getElementById("location3").innerHTML = "Wegbeschreibung";
}

function change_text_slo(){
    document.getElementById("seeMore").innerHTML = "Poglej več";
    document.getElementById("seeMore2").innerHTML = "Poglej več";
    document.getElementById("seeMore3").innerHTML = "Poglej več";
    document.getElementById("stosija").innerHTML = " Sveta Stošija ali sveta Anastazija je bila krščanska mučenica in svetnica, ki je umrla v Sirmiju med Dioklecijanovimi preganjanji. Na Hrvaškem je znana kot Sveta Stošija.<br>Na Hrvaškem je znana kot Sveta Stošija. <br><br> O Anastazijinem življenju je malo zanesljivih podatkov, razen časa njene smrti. Namesto tega obstajajo legende, večinoma datirane stoletja po njeni smrti. Po njihovem mnenju je bila rojena v Rimu ali Sirmiju, torej rimska državljanka patricijskega ranga. Po eni legendi je bila hči nekega Preteksta in učenka svetega Krševana (Chryzogon). V katoliški tradiciji je navedeno, da je bila njena mati sv. Faust iz Sirmija.";
    document.getElementById("stosija2").innerHTML ="Na najvišji vzpetini biogradskega polotoka v središču mesta je župnijska cerkev sv. Stošije je bila posvečena leta 1761. Okoli cerkve so ostanki pokopališča iz 6. stoletja, poleg cerkve pa je visok kamnit zvonik, zgrajen iz kamenja nekdanje biograjske stolnice, ki je bila na tem mestu. Kamen te stolnice, zgrajene na temeljih starokrščanske cerkve, je bil vgrajen tudi v župnijsko cerkev, na vrhu katere pročelja je kip sv. Stošije, župnija pa ima v lasti tudi svetnikov relikviarij. Češčenje sv. Posmrtne ostanke so prinesli Zadrani, ki so se v Biograd zatekli v 12. stoletju, ko so Benečani prevzeli Zadar.";
    document.getElementById("stosijaNaslov").innerHTML = "Cerkev Sv. Stošije";
    document.getElementById("moreStosija").innerHTML = "<br><br>Sveta Stošija ili Sveta Anastazija bila je kršćanska mučenica i svetica koja je umrla u Sirmiumu za vrijeme Dioklecijanovih progona. U Hrvatskoj je poznata kao Sveta Stošija. <br><br><br>Na najvišoj uzvisini biogradskoga poluotoka u središtu grada nalazi se župna crkva sv. Stošije posvećena 1761. g. Oko crkve su ostatci groblja iz 6. st., a uz crkvu je visoki kameni zvonik izgrađen od kamenja nekadašnje biogradske katedrale koja je bila na tom mjestu. Kamen te katedrale podignute na temeljima starokršćanske crkve ugrađen je i u župnu crkvu na čijem je vrhu pročelja kip sv. Stošije, a župa posjeduje i svetičin relikvijar. Čašćenje sv. Stošije donijeli su Zadrani koji su se sklonili u Biograd u 12. st. kad su Mlečani srušili Zadar.";
    document.getElementById("muzejNaslov").innerHTML = "Zavičajni muzej";
    document.getElementById("muzej").innerHTML = " Zavičajni muzej mesta Biograd na Moru je samostojna in edina kulturna ustanova na območju Biograda. Hrani dragoceno spomeniško dediščino iz bogate preteklosti biograjske obale in okolice. <br> <br> <br> Nahaja se v osrednjem delu, na sami obali Biograda, nekdanjega kraljevskega in kronalnega mesta, prestolnice hrvaške države za ljudskih vladarjev v 11. stoletju. Sama stavba, v kateri je muzej, je kulturni spomenik. Zgrajena je bila na ruševinah srednjeveškega obzidja konec 18. in v začetku 19. stoletja. Dolga leta je v njem delovalo okrožno sodišče, ustanovljeno za cesarja in kralja Franca Josipa I. - leta 1876.";
    document.getElementById("moreMuzej").innerHTML = " <br>Zavičajni muzej Grada Biograda na Moru, samostalna je i jedina ustanova u kulturi na biogradskom području. Čuva vrijednu spomeničku baštinu iz bogate prošlosti biogradskog primorja i okolice. <br> <br> <br> Smješten je u centralnom djelu, na samoj obali Biograda, nekadašnjeg kraljevskog i krunidbenog grada, prijestolnice hrvatske države za narodnih vladara u 11. stoljeću. Sama zgrada u kojoj je smješten Muzej spada u spomenik kulture. Podignuta je na ruševinama srednjovjekovnih zidina pri kraju 18. i početkom 19. stoljeća. U njoj je dugi niz godina djelovao Kotarski sud uspostavljen za cara i kralja Franje Josipa I -1876. godine.";
    document.getElementById("rokoNaslov").innerHTML = "Cerkev sv. Roka";
    document.getElementById("roko").innerHTML = " <br>Najstarejša omemba cerkve je namreč v oporoki, napisani leta 1653, v kateri Franica, žena Ivana Senjana, zapušča cerkvi pridelek oljk: „Cerkvi svetega Roka, ki je pred našo vasjo.“. <br><br> Posvečena sv. Roku, zaščitniku pred kugo, je bila zgrajena v poznem 16. ali začetku 17. stoletja. V notranjosti cerkve dominira pozlačen baročni oltar iz 18. stoletja, okoli cerkve pa je več dreves s klopmi za posedanje, tako da celoten prostor daje vtis mini parka.";
    document.getElementById("moreRoko").innerHTML = " <br><br><br>Najraniji spomen crkve nalazi se u oporuci pisanoj 1653. godine, u kojoj Franica, žena Ivana Senjanina, ostavlja urod od maslina: „Crikvi svetoga Roka ka je prid selom našim“. <br><br> Posvećena svetom Roku, zaštitniku od kuge, sagrađena je krajem 16. ili početkom 17. stoljeća. Unutrašnjošću crkve dominira pozlaćeni barokni oltar iz 18. stoljeća. a oko crkvice nalazi se nekoliko stabala sa klupama za sjedenje, pa cijeli prostor odaje dojam mini parka. ";
    document.getElementById("location").innerHTML = "Navodila do lokacije";
    document.getElementById("location2").innerHTML = "Navodila do lokacije";
    document.getElementById("location3").innerHTML = "Navodila do lokacije";
}




